# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту
  #nataliya.andmail@gmail.com если сборка упала
notifications:
  email:
    recipients:
      nataliya.andmail@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    802a869c-03ce-4431-9355-fd6debb1a7dd